"""add_timezone

Revision ID: 99f7aeba0981
Revises: a4d495019431
Create Date: 2026-05-16 21:02:45.688726

"""

from alembic import op
import sqlalchemy as sa


revision = "99f7aeba0981"
down_revision = "a4d495019431"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.DATE(),
        type_=sa.DateTime(timezone=True),
        nullable=True,
    )
    op.create_unique_constraint(None, "users", ["username"])
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DATE(),
        nullable=False,
    )
    op.drop_column("users", "updated_at")
    # ### end Alembic commands ###
