"""workout_user_id_nullable

Revision ID: a4d495019431
Revises: 06ab2a1063a8
Create Date: 2026-05-16 20:37:33.529826

"""

from alembic import op
import sqlalchemy as sa


revision = "a4d495019431"
down_revision = "06ab2a1063a8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workouts", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "workouts", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workouts", type_="foreignkey")
    op.drop_column("workouts", "user_id")
    # ### end Alembic commands ###
